stages:
  - test_and_build
  - pack_and_push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  TAG: v${CI_PIPELINE_ID}
  PROD_NAMESPACE: prod
  STAGE_NAMESPACE: stage
  DEV_NAMESPACE: develop
  RULES_CHANGES_PATH: "**/*"

#============================================================================= templates

.test_and_build_template:
  script: &test_and_build_definition
    - cd $PROJECT_NAME
    - dotnet nuget remove source Artifactory
    - dotnet nuget add source https://repo.mofid.dev/artifactory/api/nuget/v3/nuget --name Artifactory
    - dotnet restore
    #- dotnet test --configuration Release --no-build --no-restore
    - dotnet build --configuration Release --no-restore

.pack_and_push_template:
  script: &pack_and_push_definition
    - cd $PROJECT_NAME
    - dotnet nuget remove source Artifactory
    - dotnet nuget add source https://repo.mofid.dev/artifactory/api/nuget/v3/nuget --name Artifactory
    - dotnet restore
    #- dotnet test --configuration Release --no-build --no-restore
    - dotnet build --configuration Release --no-restore
    - dotnet pack --configuration Release --output out --no-build --no-restore
    - dotnet nuget push out/*.nupkg -s Artifactory --skip-duplicate

#============================================================================= build

test.and.build.CacheKeys:
  stage: test_and_build
  image: docker.mofid.dev/mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - mofidapp_docker_runner
  variables:
    PROJECT_NAME: CacheKeys
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    changes:
      - CacheKeys/**/*
  script:
    - *test_and_build_definition

test.and.build.Core:
  stage: test_and_build
  image: docker.mofid.dev/mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - mofidapp_docker_runner
  variables:
    PROJECT_NAME: Core
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    changes:
      - Core/**/*
  script:
    - *test_and_build_definition

test.and.build.TestHelper:
  stage: test_and_build
  image: docker.mofid.dev/mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - mofidapp_docker_runner
  variables:
    PROJECT_NAME: TestHelper
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
    changes:
      - TestHelper/**/*
  script:
    - *test_and_build_definition

#============================================================================= push

pack.and.push.CacheKeys:
  stage: pack_and_push
  image: docker.mofid.dev/mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - mofidapp_docker_runner
  variables:
    PROJECT_NAME: CacheKeys
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    changes:
      - CacheKeys/**/*
  when: manual
  script:
    - *pack_and_push_definition

pack.and.push.Core:
  stage: pack_and_push
  image: docker.mofid.dev/mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - mofidapp_docker_runner
  variables:
    PROJECT_NAME: Core
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    changes:
      - Core/**/*
  when: manual
  script:
    - *pack_and_push_definition

pack.and.push.TestHelper:
  stage: pack_and_push
  image: docker.mofid.dev/mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - mofidapp_docker_runner
  variables:
    PROJECT_NAME: TestHelper
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    changes:
      - TestHelper/**/*
  when: manual
  script:
    - *pack_and_push_definition
